config/routes.rb
Rails.application.routes.draw do

  #スタート画面
  root to: 'chat#home'

  get 'chat/home' , to: 'chat#home'

  #新規コメント用
  get 'chat/add' , to: 'chat#home'#再読み込み回避用
  post 'chat/add' , to: 'chat#add'
  #登録・ログイン用
  post 'chat/registlogin' , to: 'chat#registlogin'
  #コメント削除
  delete 'chat/home' , to: 'chat#destroy'

  #(登録、)ログイン、ログアウト用
  get 'sessions/registlogin' , to: "chat#home"#再読み込み回避用
  post 'sessions/registlogin' , to: "sessions#registlogin"
  post "sessions/logout" , to: "sessions#logout"



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chatlog.rb
class Chatlog < ApplicationRecord
    #コメントの文字数制限
    validates :text ,  presence: true , length: {maximum: 100}
end

app/models/user.rb
class User < ApplicationRecord
#パスワードを暗号化する
  #文字数制限
  validates :name , presence: true , uniqueness: true ,   length: {maximum: 10}
  has_secure_password
  #validates :password , presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chat_controller.rb
class ChatController < ApplicationController
  def home
  end

  #コメント追加時
  def add
    @chat = Chatlog.new(chat_params)
    #名前にユーザー名を入れる(ログインしていなかったらnil)
    @chat.name = session[:user_name]
    if @chat.save
      redirect_to chat_home_path()
    else
      render action: "home"
    end
  end

  #コメント削除
  def destroy
    @chat = Chatlog.find(params[:id])
    @chat.destroy
    redirect_to chat_home_path()
  end

  private
  def chat_params#変数二つをクラスにまとめて返す
    params.require(:chatlog).permit(:name , :text)
  end


end

app/controllers/sessions_controller.rb
#session管理コントローラー
class SessionsController < ApplicationController

  #ユーザー登録、ログイン判定
  def registlogin
    @user = User.new(user_params)
    search_user = User.find_by(name: @user.name)
    if params[:commit] == " 登録 "
      if @user.save
        flash[:login_notice] =  "「#{@user.name}」を登録しました"
        #@user.save
        redirect_to chat_home_path()
      else
        render template: "chat/home"
      end
    elsif params[:commit] == "ログイン"
      search_user = User.find_by(name: @user.name)
      #ユーザー名とパスワード確認
      if search_user && search_user.authenticate(@user.password)
        flash[:login_notice] =  "#{@user.name}でログインしました"
        session[:user_name] = @user.name
        redirect_to chat_home_path()
      else
        if search_user
          @user.errors.add(:password , "が間違っています")
        else
          @user.errors.add(:name , "「#{@user.name}」は登録されていません")
        end
          session[:user_name] = nil
          render template: "chat/home"
      end
    else
      redirect_to chat_home_path()
    end
  end


  #ログアウト
  def logout
    session[:user_name] = nil
    redirect_to chat_home_path()
  end

  private
  def user_params#変数二つをクラスにまとめて返す
    params.require(:user).permit(:name , :password)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_helper.rb
module ChatHelper
end

app/views/chat/home.html.erb
<%#>チャット用ページ <%>
<div class='title'>フリーチャット</div>

<%# テーブルの読み取り %>
<%@chatlog = Chatlog.all unless @chatlog%>
<%@user = User.new() unless @user%>
<%@chat = Chatlog.new() unless @chat%>

<%# ログイン状況で反応を変更 %>
<% if(session[:user_name] != nil) %>
	ようこそ「<%= session[:user_name] %>」さん。<br>
	ログインせずにしたコメントは誰でも削除できます。<br>
	ログインして行ったコメントは本人しか削除できません。<br>
	<div class='user-zone'>
		<div class="user-zone-title">ログイン中…</div>
		<div class = "user-zone-main">
			<% if @user.errors.any?  || flash[:login_notice] %><%#>警告などあればここに表示<%>
				<div class="alert alert-warning text_center">
					<% if @user.errors.any? %><%#>警告などあればここに表示<%>
   						<% @user.errors.full_messages.each do |message| %>
       						<li><%= message %></li>
   						<% end %>
					<%end%>
					<%if flash[:login_notice] %><%#>警告などあればここに表示<%>
						<li>*<%= flash[:login_notice]%>*</li>
					<% end %>
				</div>
			<%end%>
	  		<%= session[:user_name] %>さん<%= button_to "ログアウトする" , sessions_logout_path , method: :post%>
		</div>
	</div>
<% else %>
	ようこそ「匿名ユーザー」さん。<br>
	ログインせずにしたコメントは誰でも削除できます。<br>
	ログインして行ったコメントは本人にしか削除できません。<br>
	<div class='user-zone'>
		<div class="user-zone-title">ユーザー登録・ログイン</div>
		<div class = "user-zone-main">
			<% if @user.errors.any? || flash[:login_notice] %>
				<div class="alert alert-warning text_center">
					<% if @user.errors.any? %><%#>警告などあればここに表示<%>
      					<% @user.errors.full_messages.each do |message| %>
        					<li><%= message %></li>
      					<% end %>
					<%end%>
					<%if flash[:login_notice] %><%#>警告などあればここに表示<%>
						<li>*<%= flash[:login_notice]%>*</li>
					<% end %>
				</div>
			<%end%>
			<%= form_for(@user, url: sessions_registlogin_path , method: :post) do |f| %>
				<table class = "block_center"><tr>
					<td><%= f.text_field :name , :placeholder => "ユーザー名" , :maxlength => 10%></td>
					<td><%= f.password_field :password , :placeholder => "パスワード"%></td>
				</tr></table>
				<font size = "2">*ユーザー名は10字以内</font><br>
				<%= submit_tag " 登録 "%> or <%= submit_tag "ログイン"%>
			<% end %>
		</div>
	</div>
<% end %>

<%# コメント入力欄 %>
<%= form_for(@chat , url: chat_add_path , method: :post) do |f| %>
	<table class = 'chat_input'>
		<% if @chat.errors.any? %><%#>警告などあればここに表示<%>
			<div class="alert alert-warning text_center">
   				<% @chat.errors.full_messages.each do |message| %>
       				<li><%= message %></li>
   				<% end %>
			</div>
		<% end %>
   		<tr>
	   		<td><%= f.text_area :text , :placeholder => "入力欄(100字以内)" , :maxlength => 100 , size: "30x3"%></td>
			<td><%= f.submit "　コメントする　"%></td>
		</tr>
	</table>
<% end %>


<div class = 'chat_zone container-fluid'>
<div class = chat_zone-title>チャット覧</div>

<table>
	<%#新しいコメントが上に来るようにreverse  %>
	<% @chatlog.reverse.each do |chat| %>
		<tr><%#>リスト配置 %>
	  		<%# 名前部分 %>
			<td class = min_td>
    			<% if chat.name == nil || chat.name == "" %>
				 	「　」
    			<% else %>
        			<%= chat.name %>
  		  		<% end %>
			</td>
			<%# コメント部分 %>
  			<td class="balloon1">
   				<%=simple_format(chat.text)%>
  			</td>
			<td class = min_td>
				<%# 削除ボタンの表示判定（コメ主がいないor同一人物or管理者なら表示） %>
    			<% if( chat.name == nil || chat.name == "" || session[:user_name] == chat.name || session[:user_name] == "admin")%>
    				<%= link_to "[削除]" , chat_home_path(id: chat , name: session[:user_name]) , method: :delete %>
	    		<% end %>
			</td>
		</tr>
	<% end %>
</table>

app/views/layouts/application.html.erb
<%# ヘッダー %>
<!DOCTYPE html>
<html>
  <head >
    <title>FreeChatRoom</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta http-equiv='Content-Type' content='text/html; charset=UTF-8' />
    <meta name='viewport' content='width=device-width,initial-scale=1'>


    <% title_word = "ゆっくりしていってね!"%>
    <%tmp = Time.current.in_time_zone("Asia/Tokyo") %>
    <%time = "#{tmp.year}/#{tmp.month}/#{tmp.day}"%>
    <header class='whole-head'>
      <div class = 'container-fluid'><%#ヘッダー固定用の下敷き %>
        <span class='ribbon1'>★</span><span class='ribbon2'>★</span>
        <div class = 'header_contents'>
          <div class='header-center'><%=title_word%></div>
          <div class = 'header-right'><%=time%></div>
        </div>
      </div>

      <div class = 'container-fluid site-header'>
        <span class='ribbon1'>★</span><span class='ribbon2'>★</span>
        <div class = 'header_contents'>
          <div class='header-center'><%=title_word%></div>
          <div class = 'header-right'><%=time%></div>
        </div>
      </div>
      </div>

    </header>
  </head>
  <body class = whole-page>

  <div class = 'container-fluid'>
    <div class='main-content'>
      <%= yield %><%#>ここに各ページの内容が入る<%>
    </div>
  </div>

  </body>
</html>